spring.application.name=sg_cdez_api
spring.datasource.url=jdbc:postgresql://localhost:5432/anaconda
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update