spring.application.name=sg_cdez_api
spring.datasource.url=jdbc:postgresql://localhost:5432/anaconda
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

#jwt token secret con expiración de 30 mins (en milisegundos)
jwt.secret=${SECRET_KEY}
jwt.expiration=1800000

